import { Tournament } from './types';

export const TOTAL_POT = 4800;
export const TOTAL_PLAYERS = 48;

export const SITE_PASSWORD = process.env.NEXT_PUBLIC_SITE_PASSWORD || 'hellofriends';

export const TOURNAMENTS: Tournament[] = [
  {
    id: 'masters-2026',
    name: 'The Masters',
    shortName: 'Masters',
    slug: 'masters-2026',
    startDate: '2026-04-09',
    endDate: '2026-04-12',
    isMajor: true,
    multiplier: 1.25,
    status: 'in_progress',
    currentRound: 1,
    updatedAt: '2026-04-09T20:00:00Z',
  },
  {
    id: 'rbc-heritage-2026',
    name: 'RBC Heritage',
    shortName: 'Heritage',
    slug: 'rbc-heritage-2026',
    startDate: '2026-04-16',
    endDate: '2026-04-19',
    isMajor: false,
    multiplier: 1.0,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'truist-2026',
    name: 'Truist Championship',
    shortName: 'Truist',
    slug: 'truist-2026',
    startDate: '2026-05-07',
    endDate: '2026-05-10',
    isMajor: false,
    multiplier: 1.0,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'pga-championship-2026',
    name: 'PGA Championship',
    shortName: 'PGA',
    slug: 'pga-championship-2026',
    startDate: '2026-05-14',
    endDate: '2026-05-17',
    isMajor: true,
    multiplier: 1.25,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'charles-schwab-2026',
    name: 'Charles Schwab Challenge',
    shortName: 'Schwab',
    slug: 'charles-schwab-2026',
    startDate: '2026-05-28',
    endDate: '2026-05-31',
    isMajor: false,
    multiplier: 1.0,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'rbc-canadian-2026',
    name: 'RBC Canadian Open',
    shortName: 'Canadian',
    slug: 'rbc-canadian-2026',
    startDate: '2026-06-11',
    endDate: '2026-06-14',
    isMajor: false,
    multiplier: 1.0,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'us-open-2026',
    name: 'U.S. Open',
    shortName: 'US Open',
    slug: 'us-open-2026',
    startDate: '2026-06-18',
    endDate: '2026-06-21',
    isMajor: true,
    multiplier: 1.25,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'travelers-2026',
    name: 'Travelers Championship',
    shortName: 'Travelers',
    slug: 'travelers-2026',
    startDate: '2026-06-25',
    endDate: '2026-06-28',
    isMajor: false,
    multiplier: 1.0,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'scottish-open-2026',
    name: 'Genesis Scottish Open',
    shortName: 'Scottish',
    slug: 'scottish-open-2026',
    startDate: '2026-07-09',
    endDate: '2026-07-12',
    isMajor: false,
    multiplier: 1.0,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
  {
    id: 'the-open-2026',
    name: 'The Open Championship',
    shortName: 'The Open',
    slug: 'the-open-2026',
    startDate: '2026-07-16',
    endDate: '2026-07-19',
    isMajor: true,
    multiplier: 1.25,
    status: 'upcoming',
    currentRound: 0,
    updatedAt: '',
  },
];

export const PAYOUTS = {
  major: {
    first: { pct: 8, amount: 384 },
    second: { pct: 4, amount: 192 },
  },
  nonMajor: {
    first: { pct: 2, amount: 96 },
  },
  season: {
    first: { pct: 20, amount: 960 },
    second: { pct: 12, amount: 576 },
    third: { pct: 8, amount: 384 },
  },
};

export const CHALK_THRESHOLD = 25;
export const CONTRARIAN_THRESHOLD = 10;
